---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create a wordpress LAMP stack using EC2'

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access + ssh acess
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  WebServer: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: "ami-067f5c3d5a99edc80"
      InstanceType: "t2.small"
      KeyName: "CloudFormation"
      SecurityGroups: 
        - !Ref 'WebServerSecurityGroup'
  IPAddress:
    Type: 'AWS::EC2::EIP'
  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref 'WebServer'
      EIP: !Ref 'IPAddress'
